blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^delete/(?P<delete_id>[0-9])$', views.delete, name="delete"),
    url(r'^update/(?P<update_id>[0-9])$', views.update, name="update"),
	url(r'^category/(?P<categoryInput>[\w-]+)/$',views.categoryPost, name="category"),
	url(r'^post/(?P<postInput>[0-9])/$',views.singlePost, name="post"),
	url(r'^create/$',views.create,name="create"),
    # semua angka
    # url(r'^(?P<input>[0-9]+)/$', views.angka),
    # limit angka
    url(r'^(?P<input>[0-9]{2})/$', views.angka),
    url(r'^(?P<page>[\w]+)/$', views.link),
    url(r'^(?P<tahun>[0-9]{4})/(?P<bulan>[0-9]{2})/(?P<hari>[0-9]{2})/$', views.tanggal),
]

mywebsite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^monitoring/', include('monitoring.urls', namespace='monitoring')),
    url(r'^grafik/', include('grafik.urls', namespace='grafik')),
    url(r'^about/', include('about.urls')),
    url(r'^$', views.index, name="index"),
    url(r'^login/$', views.login, name="login")
]

blog/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    category = models.CharField(max_length=20, blank=True)
    email = models.EmailField(default='nama@web.com')
    alamat = models.CharField(max_length=200, blank=True)
    waktu_posting = models.DateTimeField(auto_now_add=True)
    waktu_update = models.DateTimeField(auto_now= True)


    def __str__(self):
        return "{} . {}".format(self.id,self.title)

blog/forms.py
from django import forms

from .models import Post
# class PostForm(forms.Form):
#     title = forms.CharField(max_length= 20)
#     body = forms.CharField(
#         widget = forms.Textarea
#     )
#     category = forms.CharField(max_length= 20)

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'body',
            'category'
        ]

blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.http import HttpResponseRedirect
# Create your views here.
from .models import Post
from .forms import PostForm
def index(request):

    posts= Post.objects.all()
    # print(posts)
    context = {
        'title'          : 'Blog',
        'active_blog'    : 'active',
        'posts'          : posts,
        'category'       : 'All'
    }
    return render(request,'blog/index.html',context)
def create(request):
    post_form = PostForm(request.POST or None)
    if request.method=='POST':
        Post.objects.create(
            title       = request.POST['title'],
            body        = request.POST['body'],
            category    = request.POST['category'],
        )
        return HttpResponseRedirect('/blog')
    else:
        pass
    context = {
        'title'          : 'Tambah',
        'active_blog'    : 'active',
        'post_form'      : post_form
    }
    return render(request,'blog/create.html',context)
def delete(request,delete_id):
    Post.objects.filter(id=delete_id).delete()
    return HttpResponseRedirect('/blog')
def update(request,update_id):
    post = Post.objects.get(id=update_id)
    data = {
        'title' : post.title,
        'body'  : post.body,
        'category' : post.category
    }
    post_form = PostForm(request.POST or None, initial = data, instance=post)
    if request.method=='POST':
        post_form.save()
        return HttpResponseRedirect('/blog')
    else:
        pass
    context = {
        'title'          : 'Update',
        'active_blog'    : 'active',
        'post_form'      : post_form
    }
    return render(request,'blog/create.html',context)
def link(request,page):
    heading = "<h1>Page  {} </h1>".format(page)
    # str = heading + input
    return HttpResponse(heading)
def angka(request,input):
    heading = "<h1>Page Angka</h1>"
    str = heading + input
    return HttpResponse(str)
def tanggal(request,**input):
    heading = "<h1>Page Tanggal</h1>"
    strTahun = "tahun : " + input['tahun']
    strBulan = "Bulan : " + input['bulan']
    strHari = "Hari : " + input['hari']
    dateTanggal = "{}/{}/{}".format(input['tahun'],input['bulan'],input['hari'])
    str = heading + strTahun + "<br>" + strBulan + "<br>" +strHari
    return HttpResponse(heading + dateTanggal)
# def tanggal(request,tahun,bulan,hari):
#     heading = "<h1>Page Tanggal</h1>"
#     strTahun = "tahun : " + tahun
#     strBulan = "Bulan : " + bulan
#     strHari = "Hari : " + hari
#     str = heading + strTahun + "<br>" + strBulan + "<br>" +strHari
#     return HttpResponse(str)
def categoryPost(request,categoryInput):

    posts= Post.objects.filter(category=categoryInput)
    # print(posts)
    context = {
        'title'          : 'Blog',
        'heading'        :'ini adalah blog kelas terbuka',
        'subheading'     : '1 April 2019',
        'active_blog'    : 'active',
        'posts'          : posts,
        'category'       : categoryInput
    }
    return render(request,'blog/index.html',context)
def singlePost(request,postInput):

    posts= Post.objects.get(id=postInput)
    # print(posts)
    context = {
        'title'          : 'Blog',
        'heading'        :'ini adalah blog kelas terbuka',
        'subheading'     : '1 April 2019',
        'active_blog'    : 'active',
        'posts'          : posts,
        'category'       : postInput
    }
    return render(request,'blog/detail.html',context)

blog/templates/blog/create.html
{% extends 'base.html' %}

{% block contents %}

<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
      <div class="card mb-3">
          <div class="card-header card-header-divider"> {{title}}
              <div style="float:right">
                <a class="btn btn-sm btn-primary" href="javascript:history.back()"><i class="mdi mdi-flip-to-back"></i> Kembali</a>
              </div>
            </div>
            <div class="card-body">
              <form method="post">
                {% csrf_token %}
                <table>
                  {{post_form}}
                </table>
                <button type="submit">Kirim</button>
              </form>
                </div>
  </div>
</div>
{% endblock contents %}

blog/templates/blog/detail.html
{% extends 'base.html' %}

{% block contents %}

<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
      <div class="card mb-3">
          <div class="card-header card-header-divider"> {{posts.title}} {{ request.get_full_path }}
              <div style="float:right">
                <a class="btn btn-sm btn-primary" href="javascript:history.back()"><i class="mdi mdi-flip-to-back"></i> Kembali</a>
              </div>
            </div>
          <div class="card-body">
              <p class="lead">{{posts.body}}</p>
            </div>
  </div>
</div>
{% endblock contents %}

blog/templates/blog/index.html
{% extends 'base.html' %}

{% block contents %}

<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
      <div class="card mb-3">
          <div class="card-header card-header-divider">BLog {{category}}

          </div>
          <div class="card-body">
                <table class="table table-responsive-xl table-bordered">
                  <thead>
                    <tr>
                      <th width="10px">No</th>
                      <th  width="100px">Title </th>
                      <th>Body</th>
                      <th>Category</th>
                      <th>Waktu Posting</th>
                      <th width="10% "> <a href="{% url "blog:create" %}" class="btn btn-success btn-sm"><i class="mdi mdi-plus"></i> Tambah</a></th>
                    </tr>
                  </thead>
                  <tbody>

                    {% for post in posts %}
                      <tr>
                        <td align="center">{{forloop.counter}}</td>
                        <td><a href="{% url "blog:post" postInput=post.id %}">{{post.title}}</a></td>
                        <td>{{post.body}}</td>
                        <td><a href="{% url "blog:category" categoryInput=post.category %}">{{post.category}}</a></td>
                        <td>{{post.waktu_posting}}</td>
                        <td align="center">
                          <div class="btn-group">
                            <a href="{% url "blog:update" update_id=post.id %}" class="btn btn-xs btn-success">
                              <i class="mdi mdi-edit"></i>
                            </a>
                            <a href="{% url "blog:delete" delete_id=post.id %}" class="btn btn-xs btn-danger" onclick="javasciprt: return confirm('apakah anda yakin untuk menghapus ?')">
                              <i class="mdi mdi-delete"></i>
                            </a>
                          </div>
                        </td>
                      </tr>
                    {% endfor %}

                  </tbody>
                </table>
      </div><!-- end card-->
  </div>
</div>
{% endblock contents %}