blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^delete/(?P<delete_id>[0-9])$', views.delete, name="delete"),
    url(r'^update/(?P<update_id>[0-9])$', views.update, name="update"),
	url(r'^category/(?P<categoryInput>[\w-]+)/$',views.categoryPost, name="category"),
	url(r'^post/(?P<postInput>[0-9])/$',views.singlePost, name="post"),
	url(r'^create/$',views.create,name="create"),
    # semua angka
    # url(r'^(?P<input>[0-9]+)/$', views.angka),
    # limit angka
    url(r'^(?P<input>[0-9]{2})/$', views.angka),
    url(r'^(?P<page>[\w]+)/$', views.link),
    url(r'^(?P<tahun>[0-9]{4})/(?P<bulan>[0-9]{2})/(?P<hari>[0-9]{2})/$', views.tanggal),
]

grafik/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^grafik1/$', views.grafik1, name="grafik1"),
    url(r'^grafik2/$', views.grafik2, name="grafik2"),
    url(r'^grafik2/(?P<opd_id>[0-9]+)/$', views.grafik2, name="grafik2"),
    url(r'^grafik3/$', views.grafik3, name="grafik3"),
    url(r'^grafik4/$', views.grafik4, name="grafik4"),
]

monitoring/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^rekapAjuan/$', views.rekapAjuan, name="rekapAjuan"),
    url(r'^excel_view/$', views.excel_view, name="excel_view"),
    url(r'^rekapAjuanopd/$', views.rekapAjuanopd, name="rekapAjuanopd"),
    url(r'^rekapAjuanopd/(?P<opd_id>[0-9]+)/$', views.rekapAjuanopd, name="rekapAjuanopd"),
    url(r'^excel_view_rekapAjuanopd/(?P<opd_id>[0-9]+)/$', views.excel_view_rekapAjuanopd, name="excel_view_rekapAjuanopd"),
    url(r'^rekapAjuanKegiatanopd/$', views.rekapAjuanKegiatanopd, name="rekapAjuanKegiatanopd"),
    url(r'^rekapAjuanKegiatanopd/(?P<opd_id>[0-9]+)/$', views.rekapAjuanKegiatanopd, name="rekapAjuanKegiatanopd"),
    url(r'^excel_view_rekapAjuanKegiatanopd/(?P<opd_id>[0-9]+)/$', views.excel_view_rekapAjuanKegiatanopd, name="excel_view_rekapAjuanKegiatanopd"),
    url(r'^kegiatanEntry/$', views.kegiatanEntry, name="kegiatanEntry"),
    url(r'^kegiatanEntry/(?P<opd_id>[0-9]+)/$', views.kegiatanEntry, name="kegiatanEntry"),
    url(r'^excel_view_kegiatanEntry/(?P<opd_id>[0-9]+)/$', views.excel_view_kegiatanEntry, name="excel_view_kegiatanEntry"),

    url(r'^renja2/$', views.renja2, name="renja2"),
    url(r'^renja2/(?P<opd_id>[0-9]+)/$', views.renja2, name="renja2"),
    url(r'^excel_view_renja2/(?P<opd_id>[0-9]+)/$', views.excel_view_renja2, name="excel_view_renja2"),
    #
    url(r'^rekapAjuan/$', views.rekapAjuan, name="rekapAjuan"),
]

mywebsite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^monitoring/', include('monitoring.urls', namespace='monitoring')),
    url(r'^grafik/', include('grafik.urls', namespace='grafik')),
    url(r'^about/', include('about.urls')),
    url(r'^$', views.index, name="index"),
    url(r'^login/$', views.login, name="login")
]

templates/snippets/scripts.html
{% load static %}
<script src="{% static 'assets/lib/jquery/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/lib/bootstrap/dist/js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/js/app.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/lib/jquery-flot/jquery.flot.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/lib/jquery-flot/jquery.flot.pie.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/lib/jquery-flot/jquery.flot.time.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/lib/jquery-flot/jquery.flot.resize.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/lib/jquery-flot/plugins/jquery.flot.orderBars.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/lib/jquery-flot/plugins/curvedLines.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/lib/jquery-flot/plugins/jquery.flot.tooltip.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/lib/jquery.sparkline/jquery.sparkline.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/lib/countup/countUp.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/lib/jquery-ui/jquery-ui.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/lib/jqvmap/jquery.vmap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/lib/jqvmap/maps/jquery.vmap.world.js' %}" type="text/javascript"></script>
<script type="text/javascript">
  $(document).ready(function(){
      //-initialize the javascript
      App.init();
      App.dashboard();

  });
</script>

templates/snippets/sidebar.html
<div class="be-left-sidebar">
  <div class="left-sidebar-wrapper"><a class="left-sidebar-toggle" href="#">Dashboard</a>
    <div class="left-sidebar-spacer">
      <div class="left-sidebar-scroll">
        <div class="left-sidebar-content">
          <ul class="sidebar-elements">
            <li class="divider">Menu</li>
            <li class="{{active_dashboard}}"><a href="{% url "index" %}"><i class="icon mdi mdi-home"></i><span>Dashboard</span></a>
            </li>
            <li class="{{active_blog}}"><a href="{% url "blog:index" %}"><i class="icon mdi mdi-home"></i><span>Blog</span></a>
            </li>
            <li class="parent">
              <a href="#">
                <i class="mdi mdi-collection-text"></i>
                <span>Monitoring Renja</span>
                <span class="menu-arrow"></span>
              </a>
              <ul class="sub-menu" style="">
                <li class="{{active_rekapAjuan}}">
                  <a href="{% url "monitoring:rekapAjuan" %}" class="nav-link ">
                    <i class="mdi mdi-chevron-right"></i> <span>Rekapitulasi Ajuan</span>
                  </a>
                </li>
                <li class="{{active_rekapAjuanopd}}">
                  <a href="{% url "monitoring:rekapAjuanopd" %}" class="nav-link ">
                    <i class="mdi mdi-chevron-right"></i> <span>Ajuan Program OPD</span>
                  </a>
                </li>
                <li class="{{active_rekapAjuanKegiatanopd}}">
                  <a href="{% url "monitoring:rekapAjuanKegiatanopd" %}" class="nav-link ">
                    <i class="mdi mdi-chevron-right"></i> <span>Ajuan Kegiatan OPD</span>
                  </a>
                </li>
                <li>
                  <a href="{% url "blog:index" %}" class="nav-link ">
                    <i class="mdi mdi-chevron-right"></i> <span>Laporan Renja</span>
                  </a>
                </li>
                <li class="{{active_renja2}}">
                  <a href="{% url "monitoring:renja2" %}" class="nav-link ">
                    <i class="mdi mdi-chevron-right"></i> <span>Laporan Renja2 </span>
                  </a>
                </li>
                <li class="{{active_kegiatanEntry}}">
                  <a href="{% url "monitoring:kegiatanEntry" %}" class="nav-link ">
                    <i class="mdi mdi-chevron-right"></i> <span>Kegiatan yg dientry <br>setelah forum OPD</span>
                  </a>
                </li>
              </ul>
            </li>
            <li class="parent">
              <a href="#">
                <i class="mdi mdi-collection-text"></i>
                <span>Grafik</span>
                <span class="menu-arrow"></span>
              </a>
              <ul class="sub-menu" style="">
                <li class="{{active_grafik1}}">
                  <a href="{% url "grafik:grafik1" %}" class="nav-link ">
                    <i class="mdi mdi-chevron-right"></i> <span>Progres Usulan / Kecamatan</span>
                  </a>
                </li>
                <li class="{{active_grafik2}}">
                  <a href="{% url "grafik:grafik2" %}" class="nav-link ">
                    <i class="mdi mdi-chevron-right"></i> <span>Progres Usulan Desa</span>
                  </a>
                </li>
                <li class="{{active_grafik3}}">
                  <a href="{% url "grafik:grafik3" %}" class="nav-link ">
                    <i class="mdi mdi-chevron-right"></i> <span>Persentase Usulan Per Bidang  </span>
                  </a>
                </li>
                <li class="{{active_grafik4}}">
                  <a href="{% url "grafik:grafik4" %}" class="nav-link ">
                    <i class="mdi mdi-chevron-right"></i> <span>10 Top Usulan / Isu</span>
                  </a>
                </li>
                <li class="{{active_grafik5}}">
                  <a href="{% url "monitoring:renja2" %}" class="nav-link ">
                    <i class="mdi mdi-chevron-right"></i> <span>Desa Belum Entry </span>
                  </a>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

templates/snippets/styles.html
{% load static %}
<link rel="stylesheet" type="text/css" href=" {% static 'assets/lib/perfect-scrollbar/css/perfect-scrollbar.css' %}"/>
<link rel="stylesheet" type="text/css" href=" {% static 'assets/lib/material-design-icons/css/material-design-iconic-font.min.css' %}"/>
<link rel="stylesheet" type="text/css" href=" {% static 'assets/lib/jquery.vectormap/jquery-jvectormap-1.2.2.css' %}"/>
<link rel="stylesheet" type="text/css" href=" {% static 'assets/lib/jqvmap/jqvmap.min.css' %}"/>
<link rel="stylesheet" type="text/css" href=" {% static 'assets/lib/datetimepicker/css/bootstrap-datetimepicker.min.css' %}"/>
<link rel="stylesheet" href=" {% static 'assets/css/app.css' %}" type="text/css"/>