blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^delete/(?P<delete_id>[0-9])$', views.delete, name="delete"),
    url(r'^update/(?P<update_id>[0-9])$', views.update, name="update"),
	url(r'^category/(?P<categoryInput>[\w-]+)/$',views.categoryPost, name="category"),
	url(r'^post/(?P<postInput>[0-9])/$',views.singlePost, name="post"),
	url(r'^create/$',views.create,name="create"),
    # semua angka
    # url(r'^(?P<input>[0-9]+)/$', views.angka),
    # limit angka
    url(r'^(?P<input>[0-9]{2})/$', views.angka),
    url(r'^(?P<page>[\w]+)/$', views.link),
    url(r'^(?P<tahun>[0-9]{4})/(?P<bulan>[0-9]{2})/(?P<hari>[0-9]{2})/$', views.tanggal),
]

grafik/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^grafik1/$', views.grafik1, name="grafik1"),
    url(r'^grafik2/$', views.grafik2, name="grafik2"),
    url(r'^grafik2/(?P<opd_id>[0-9]+)/$', views.grafik2, name="grafik2"),
    url(r'^grafik3/$', views.grafik3, name="grafik3"),
    url(r'^grafik4/$', views.grafik4, name="grafik4"),
]

monitoring/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^rekapAjuan/$', views.rekapAjuan, name="rekapAjuan"),
    url(r'^excel_view/$', views.excel_view, name="excel_view"),
    url(r'^rekapAjuanopd/$', views.rekapAjuanopd, name="rekapAjuanopd"),
    url(r'^rekapAjuanopd/(?P<opd_id>[0-9]+)/$', views.rekapAjuanopd, name="rekapAjuanopd"),
    url(r'^excel_view_rekapAjuanopd/(?P<opd_id>[0-9]+)/$', views.excel_view_rekapAjuanopd, name="excel_view_rekapAjuanopd"),
    url(r'^rekapAjuanKegiatanopd/$', views.rekapAjuanKegiatanopd, name="rekapAjuanKegiatanopd"),
    url(r'^rekapAjuanKegiatanopd/(?P<opd_id>[0-9]+)/$', views.rekapAjuanKegiatanopd, name="rekapAjuanKegiatanopd"),
    url(r'^excel_view_rekapAjuanKegiatanopd/(?P<opd_id>[0-9]+)/$', views.excel_view_rekapAjuanKegiatanopd, name="excel_view_rekapAjuanKegiatanopd"),
    url(r'^kegiatanEntry/$', views.kegiatanEntry, name="kegiatanEntry"),
    url(r'^kegiatanEntry/(?P<opd_id>[0-9]+)/$', views.kegiatanEntry, name="kegiatanEntry"),
    url(r'^excel_view_kegiatanEntry/(?P<opd_id>[0-9]+)/$', views.excel_view_kegiatanEntry, name="excel_view_kegiatanEntry"),

    url(r'^renja2/$', views.renja2, name="renja2"),
    url(r'^renja2/(?P<opd_id>[0-9]+)/$', views.renja2, name="renja2"),
    url(r'^excel_view_renja2/(?P<opd_id>[0-9]+)/$', views.excel_view_renja2, name="excel_view_renja2"),
    #
    url(r'^rekapAjuan/$', views.rekapAjuan, name="rekapAjuan"),
]

mywebsite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^monitoring/', include('monitoring.urls', namespace='monitoring')),
    url(r'^grafik/', include('grafik.urls', namespace='grafik')),
    url(r'^about/', include('about.urls')),
    url(r'^$', views.index, name="index"),
    url(r'^login/$', views.login, name="login")
]

grafik/models.py
from django.db import models

# Create your models here.

grafik/views.py
from django.shortcuts import render
from django.db import connection
from django.http import HttpResponse
from data.models import Users

def grafik1(request):
    # user = Users.object.filter(level=5)
    user=",".join(str(msg.id) for msg in Users.object.filter(level=5))
    sql='SELECT "KEC_NAMA",count("KEL_ID") as jm_kel, sum(COALESCE( rab, 0 )) as rab FROM "DATA".users LEFT JOIN (SELECT "MUSRENBANG"."DAT_USULAN"."USER_CREATED",sum("DAT_PENERIMA"."PENERIMA_RAB") as rab from "MUSRENBANG"."DAT_USULAN" LEFT JOIN "MUSRENBANG"."DAT_PENERIMA" ON "MUSRENBANG"."DAT_USULAN"."USULAN_ID"="MUSRENBANG"."DAT_PENERIMA"."USULAN_ID" where "USER_CREATED" in ('+ user +') GROUP BY "DAT_USULAN"."USER_CREATED" )a on a."USER_CREATED"="DATA".users.id LEFT JOIN "REFERENSI"."REF_KECAMATAN" ON "REFERENSI"."REF_KECAMATAN"."KEC_ID"="DATA".users."KEC_ID" WHERE level=5 GROUP BY "KEC_NAMA" ORDER BY rab asc'
    cursor = connection.cursor()
    cursor.execute(sql)
    data = cursor.fetchall()
    context = {
        'title'          : 'Progres Usulan / Kecamatan',
        'active_grafik1'    : 'active',
        'data' :data
    }
    print(data)
    return render(request,'grafik/grafik1.html',context)
def grafik2(request,opd_id=None):
    if opd_id is None:
        a='0'
        wh="where skpd_id="+a
        sql='select * from "MUSRENBANG".new_ajuan_kegiatan_opd '+wh+' order by  skpd_kode asc,program_kode asc, kegiatan_kode asc'
    else:
        user=",".join(str(msg.id) for msg in Users.object.filter(level=5,kec_id=opd_id))
        sql='SELECT name, COALESCE( rab, 0 ) as rab FROM "DATA".users LEFT JOIN ( SELECT "MUSRENBANG"."DAT_USULAN"."USER_CREATED",sum("DAT_PENERIMA"."PENERIMA_RAB") as rab from "MUSRENBANG"."DAT_USULAN" LEFT JOIN "MUSRENBANG"."DAT_PENERIMA" ON "MUSRENBANG"."DAT_USULAN"."USULAN_ID"="MUSRENBANG"."DAT_PENERIMA"."USULAN_ID" where "USER_CREATED" in ('+ user +') GROUP BY "DAT_USULAN"."USER_CREATED" )a on a."USER_CREATED"="DATA".users.id WHERE level=5 AND "KEC_ID"= '+ str(opd_id) +' ORDER BY rab asc'

    cursor = connection.cursor()
    cursor.execute(sql)
    Data = cursor.fetchall()
    cursor = connection.cursor()
    cursor.execute('select "KEC_ID","KEC_NAMA" from "REFERENSI"."REF_KECAMATAN" ORDER BY "KEC_NAMA" ASC ')
    Opd = cursor.fetchall()
    context = {
        'title'          : 'Progres Usulan Desa',
        'active_grafik2'    : 'active',
        'Data'           : Data,
        'Opd'           : Opd,
        'Opd_id'           : opd_id,
    }
    return render(request,'grafik/grafik2.html',context)
def grafik3(request):
    sql='SELECT c."BIDANG_ID" as bid_id,d."BIDANG_NAMA",count(a."USULAN_ID") as jml,sum("public".get_rab(a."USULAN_ID")) as rab FROM "MUSRENBANG"."DAT_USULAN" a JOIN "REFERENSI"."REF_KAMUS" b ON a."KAMUS_ID"=b."KAMUS_ID" JOIN "REFERENSI"."REF_ISU" c ON c."ISU_ID"=b."ISU_ID" JOIN "REFERENSI"."REF_BIDANG" d ON c."BIDANG_ID"=d."BIDANG_ID" WHERE "USULAN_TUJUAN"=6 GROUP BY  bid_id,d."BIDANG_NAMA"'
    cursor = connection.cursor()
    cursor.execute(sql)
    data = cursor.fetchall()
    context = {
        'title'          : 'Persentase Usulan Per Bidang',
        'active_grafik3'    : 'active',
        'data' :data
    }
    print(data)
    return render(request,'grafik/grafik3.html',context)

def grafik4(request):
    sql='SELECT c."ISU_ID", c."ISU_NAMA",count(a."USULAN_ID") as jml,sum("public".get_rab(a."USULAN_ID")) as rab FROM "MUSRENBANG"."DAT_USULAN" a JOIN "REFERENSI"."REF_KAMUS" b ON a."KAMUS_ID"=b."KAMUS_ID" JOIN "REFERENSI"."REF_ISU" c ON c."ISU_ID"=b."ISU_ID" WHERE "USULAN_TUJUAN"=6 GROUP BY c."ISU_ID",c."ISU_NAMA" ORDER BY rab desc LIMIT 10'
    cursor = connection.cursor()
    cursor.execute(sql)
    data = cursor.fetchall()
    context = {
        'title'          : 'TOP 10 Usulan Per Isu',
        'active_grafik4'    : 'active',
        'data' :data
    }
    print(data)
    return render(request,'grafik/grafik4.html',context)

grafik/templates/grafik/grafik1.html
{% extends 'base2.html' %}

{% block contents %}
{% load humanize %}
{% load mathfilters  %}
{% load comma_to_dot %}


<!-- <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script> -->
<script type="text/javascript">
  $(function () {
      $('#container').highcharts({
        chart: {
              type: 'bar'
          },
          title: {
              text: 'Progres Usulan Jombang Berkadang Per Kecamatan'
          },
          subtitle: {
              text: ''
          },
          xAxis: {
              categories: [
              {% for rk in data %}
  '{{rk.0}}',
{% endfor %}

              ],
              title: {
                  text: null
              }
          },
          yAxis: {
              min: 0,
              title: {
                  text: 'Nilai Usulan (Rp) (Dalam Juta)  200 x Jumlah Desa ',
                  align: 'high'
              },
              labels: {
                  overflow: 'justify'
              }
          },
          tooltip: {
              valueSuffix: ' millions'
          },
          plotOptions: {
              bar: {
                  dataLabels: {
                      enabled: true
                  }
              }
          },
          // legend: {
          //     layout: 'vertical',
          //     align: 'right',
          //     verticalAlign: 'top',
          //     x: -40,
          //     y: 80,
          //     floating: true,
          //     borderWidth: 1,
          //     backgroundColor: ((Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'),
          //     shadow: true
          // },
          credits: {
              enabled: false
          },
          series: [{
              name: 'Nilai Usulan (Rp)',
              data: [
              {% for rk in data %}
                {{rk.2|div:1000000|floatformat:2|comma_to_dot}},
              {% endfor %}

              ],
          tooltip: {
              valuePrefix: ' Rp ',
              valueSuffix: ' Juta '
          }
          }, {
              name: 'Jumlah Desa',
              data: [
              {% for rk in data %}
                {{rk.1}},
              {% endfor %}

              ],
          tooltip: {
              valueSuffix: ' Desa '
          }
          }]
      });
  });
      </script>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
      <div class="card mb-3">
          <div class="card-header card-header-divider">{{title}}
            <div class="tools float-right">
              <div class="btn-group">
                <!-- <a href="{% url "monitoring:excel_view" %}" class="btn btn-success btn-sm"><i class="mdi mdi-print"></i> Cetak</a> -->
              </div>
            </div>
          </div>
          <div class="card-body">
            <div id="container" style="min-width: 310px; max-width: 1200px; height: 1000px; margin: 0 auto"></div>
      </div><!-- end card-->
  </div>
</div>
{% endblock contents %}

grafik/templates/grafik/grafik2.html
{% extends 'base2.html' %}

{% block contents %}
{% load humanize %}
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript">
  $(function () {
      $('#container').highcharts({
          chart: {
              type: 'bar'
          },
          title: {
              text: ''
          },
          subtitle: {
              text: ''
          },
          xAxis: {
              categories: [
              {% for rk in Data %}
                '{{rk.0}}',
              {% endfor %}



              ],
              title: {
                  text: null
              }
          },
          yAxis: {
              min: 0,
              title: {
                  text: 'Nilai Usulan (Rp) (Dalam Juta) sd 200',
                  align: 'high'
              },
              labels: {
                  overflow: 'justify'
              }
          },
          tooltip: {
              valuePrefix: ' Rp ',
              valueSuffix: ' Juta '
          },
          plotOptions: {
              bar: {
                  dataLabels: {
                      enabled: true
                  }
              }
          },
          credits: {
              enabled: false
          },
          series: [{
              name: '',
              data: [
              {% for rk in Data %}
                {{rk.1}},
              {% endfor %}

]
          }]
      });
  });
      </script>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
      <div class="card mb-3">
          <div class="card-header card-header-divider">{{title}}
            <div class="tools float-right">
              <div class="btn-group">

              </div>
            </div>
          </div>
          <div class="card-body">

            <div class="row">
                <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-xl-6">
                    <div class="form-group row pt-1">
                        <label class="col-3 col-sm-3 col-form-label text-sm-right">Kecamatan</label>
                        <div class="col-12 col-sm-8 col-lg-6">
                            <select class="form-control form-control-xs" name="opd" id="opd" placeholder="OPD">

                                <option value="None" style="color:black">Pilih Kecamatan</option>
                                {% for rk in Opd %}
                                  <option
                                     value="{{rk.0}}"
                                     {% if rk.0 == Opd_id %}
                                     selected="selected"
                                     {% endif %}>{{rk.1}}</option>
                                {% endfor %}

                            </select>
                      </div>
                  </div>
            </div>
      </div><!-- end card-->

        {% if Data|length > 0 %}
        <div id="container" style="min-width: 310px; max-width: 1200px; height: 1000px; margin: 0 auto"></div>
        {% endif %}
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
        $("#opd").val("{{Opd_id}}");
     $("#opd").on('change',function(e){
        opd = $('#opd').val();
        // alert(opd);
        var url_mask = '{% url "grafik:grafik2" opd_id=1%}'.replace(/1/, opd.toString());
        window.location.href = url_mask;
      });
      // $("#print").on('click',function(e){
      //   opd = $('#opd').val();
      //   // alert(opd);
      //   if (opd=='None') {
      //     opd=0
      //   }
      //   var url_mask = '{% url "monitoring:excel_view_rekapAjuanopd" opd_id=1%}'.replace(/1/, opd.toString());
      //   window.location.href = url_mask;
      // });
  });

</script>
{% endblock contents %}

grafik/templates/grafik/grafik3.html
{% extends 'base2.html' %}

{% block contents %}
{% load humanize %}
{% load mathfilters  %}
{% load comma_to_dot %}


<script type="text/javascript">
    $(function () {
      Highcharts.setOptions({
          lang: {
              thousandsSep: '.'
          }
      });
        $('#a').highcharts({
            chart: {
                plotBackgroundColor: null,
                plotBorderWidth: null,
                plotShadow: false,
                type: 'pie'
            },
            title: {
                text: 'Persentase Usulan Per Bidang'
            },
            tooltip: {
                pointFormat: '{series.name}: <b>{point.y:,.0f}</b>'
            },
            plotOptions: {
                pie: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    dataLabels: {
                        enabled: true,
                        format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                        style: {
                            color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                        }
                    }
                }
            },  credits: {
        enabled: false
    },
            series: [{
                name: 'Nilai Usulan (Rp)',
                colorByPoint: true,
                data: [
              {% for rk in data %}
              {
                    name: '{{rk.1}}',
                    y: {{rk.3}}
                },
              {% endfor %}

              ]
            }]
        });
    });
        </script>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
      <div class="card mb-3">
          <div class="card-header card-header-divider">{{title}}
            <div class="tools float-right">
              <div class="btn-group">
                <!-- <a href="{% url "monitoring:excel_view" %}" class="btn btn-success btn-sm"><i class="mdi mdi-print"></i> Cetak</a> -->
              </div>
            </div>
          </div>
          <div class="card-body">
            <div id="a" style="min-width: 310px; max-width: 1200px; height: 500px; margin: 0 auto"></div>
      </div><!-- end card-->
  </div>
</div>
{% endblock contents %}

grafik/templates/grafik/grafik4.html
{% extends 'base2.html' %}

{% block contents %}
{% load humanize %}
{% load mathfilters  %}
{% load comma_to_dot %}


<script type="text/javascript">
    $(function () {
      Highcharts.setOptions({
          lang: {
              thousandsSep: '.'
          }
      });
        $('#a').highcharts({
            chart: {
                type: 'column'
            },
            title: {
                text: 'TOP 10 Usulan Per Isu'
            },
            xAxis: {
                categories: [
                {% for rk in data %}
                '{{rk.1}}',
              {% endfor %}
                ],
                crosshair: true
            },
            // yAxis: {
            //     min: 0,
            //     title: {
            //         text: 'Nilai Usulan (Rp)'
            //     }
            // },
            yAxis: {

              labels: {
                  formatter: function() {
                      var ret,
                          numericSymbols = [' Ribu', ' Juta', ' Milyar', ' Triliun', 'P', 'E'],
                          i = 6;
                      if(this.value >=1000) {
                          while (i-- && ret === undefined) {
                              multi = Math.pow(1000, i + 1);
                              if (this.value >= multi && numericSymbols[i] !== null) {
                                  ret = (this.value / multi) + numericSymbols[i];
                              }
                          }
                      }
                      return 'Rp ' + (ret ? ret : this.value);
                  }
              },
                            title: {
                    text: 'Nilai Usulan (Rp)'
                }

          },
            tooltip: {
                pointFormat: '{series.name}: <b>{point.y:,.0f} </b>',
                shared: true,
            },
            plotOptions: {
                column: {
                    pointPadding: 0.2,
                    borderWidth: 0
                }
            },
            series: [{
                name: 'Nilai Usulan (Rp)',
                data: [
                {% for rk in data %}
                {{rk.3}},
              {% endfor %}
                ]

            }]
        });
    });
        </script>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
      <div class="card mb-3">
          <div class="card-header card-header-divider">{{title}}
            <div class="tools float-right">
              <div class="btn-group">
                <!-- <a href="{% url "monitoring:excel_view" %}" class="btn btn-success btn-sm"><i class="mdi mdi-print"></i> Cetak</a> -->
              </div>
            </div>
          </div>
          <div class="card-body">
            <div id="a" style="min-width: 310px; max-width: 1200px; height: 500px; margin: 0 auto"></div>
      </div><!-- end card-->
  </div>
</div>
{% endblock contents %}