blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^delete/(?P<delete_id>[0-9])$', views.delete, name="delete"),
    url(r'^update/(?P<update_id>[0-9])$', views.update, name="update"),
	url(r'^category/(?P<categoryInput>[\w-]+)/$',views.categoryPost, name="category"),
	url(r'^post/(?P<postInput>[0-9])/$',views.singlePost, name="post"),
	url(r'^create/$',views.create,name="create"),
    # semua angka
    # url(r'^(?P<input>[0-9]+)/$', views.angka),
    # limit angka
    url(r'^(?P<input>[0-9]{2})/$', views.angka),
    url(r'^(?P<page>[\w]+)/$', views.link),
    url(r'^(?P<tahun>[0-9]{4})/(?P<bulan>[0-9]{2})/(?P<hari>[0-9]{2})/$', views.tanggal),
]

monitoring/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^rekapAjuan/$', views.rekapAjuan, name="rekapAjuan"),
    url(r'^excel_view/$', views.excel_view, name="excel_view"),
    url(r'^rekapAjuanopd/$', views.rekapAjuanopd, name="rekapAjuanopd"),
    url(r'^rekapAjuanopd/(?P<opd_id>[0-9]+)/$', views.rekapAjuanopd, name="rekapAjuanopd"),
    url(r'^excel_view_rekapAjuanopd/(?P<opd_id>[0-9]+)/$', views.excel_view_rekapAjuanopd, name="excel_view_rekapAjuanopd"),
    url(r'^rekapAjuanKegiatanopd/$', views.rekapAjuanKegiatanopd, name="rekapAjuanKegiatanopd"),
    url(r'^rekapAjuanKegiatanopd/(?P<opd_id>[0-9]+)/$', views.rekapAjuanKegiatanopd, name="rekapAjuanKegiatanopd"),
    url(r'^excel_view_rekapAjuanKegiatanopd/(?P<opd_id>[0-9]+)/$', views.excel_view_rekapAjuanKegiatanopd, name="excel_view_rekapAjuanKegiatanopd"),
    url(r'^kegiatanEntry/$', views.kegiatanEntry, name="kegiatanEntry"),
    url(r'^kegiatanEntry/(?P<opd_id>[0-9]+)/$', views.kegiatanEntry, name="kegiatanEntry"),
    url(r'^excel_view_kegiatanEntry/(?P<opd_id>[0-9]+)/$', views.excel_view_kegiatanEntry, name="excel_view_kegiatanEntry"),

    url(r'^renja2/$', views.renja2, name="renja2"),
    url(r'^renja2/(?P<opd_id>[0-9]+)/$', views.renja2, name="renja2"),
    url(r'^excel_view_renja2/(?P<opd_id>[0-9]+)/$', views.excel_view_renja2, name="excel_view_renja2"),
    #
    url(r'^rekapAjuan/$', views.rekapAjuan, name="rekapAjuan"),
]

mywebsite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^monitoring/', include('monitoring.urls', namespace='monitoring')),
    url(r'^grafik/', include('grafik.urls', namespace='grafik')),
    url(r'^about/', include('about.urls')),
    url(r'^$', views.index, name="index"),
    url(r'^login/$', views.login, name="login")
]

monitoring/models.py
from django.db import models

# Create your models here.

monitoring/views.py
from django.shortcuts import render
from django.db import connection
from django.http import HttpResponse

from django.contrib.auth.models import User
# Create your views here.
import xlwt

def rekapAjuanopd(request,opd_id=None):
    if opd_id is None:
        wh=''
    else:
        wh="where skpd_id="+opd_id

    cursor = connection.cursor()
    cursor.execute('select * from "MUSRENBANG".new_laporan_ajuan_program_kegiatan_opd '+ wh)
    Data = cursor.fetchall()
    cursor = connection.cursor()
    cursor.execute('select "SKPD_ID","SKPD_NAMA" from "REFERENSI"."REF_SKPD"')
    Opd = cursor.fetchall()
    context = {
        'title'          : 'Ajuan Program OPD',
        'active_rekapAjuanopd'    : 'active',
        'Data'           : Data,
        'Opd'           : Opd,
        'Opd_id'           : opd_id,
    }
    return render(request,'monitoring/rekapAjuanopd.html',context)
def excel_view_rekapAjuanopd(request,opd_id=None):
    if opd_id is '0':
        wh=''
        a='select * from "MUSRENBANG".new_laporan_ajuan_program_kegiatan_opd '+ wh
    else:
        wh="where skpd_id="+opd_id
        a='select * from "MUSRENBANG".new_laporan_ajuan_program_kegiatan_opd '+ wh
    # return HttpResponse(a)
    cursor = connection.cursor()
    cursor.execute(a)
    Data = cursor.fetchall()
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename="Ajuan Program OPD.xls"'

    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('Ajuan Program OPD', cell_overwrite_ok=True)
    # Sheet header, first row
    row_num = 0
    # borders
    borders = xlwt.Borders()
    borders.left = 1
    borders.right = 1
    borders.top = 1
    borders.bottom = 1

    font_style = xlwt.XFStyle()
    font_style.font.bold = True
    font_style.borders = borders

    columns = ['No', 'Kode OPD', 'OPD', 'Kode Porgram','Program', 'Kegiatan','Sub Kegiatan','Anggaran' ]
    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)

    #Format Currency
    style2 = xlwt.XFStyle()
    style2.num_format_str = '$#,##0.00'
    style2.borders = borders
    # Sheet body, remaining rows
    font_style = xlwt.XFStyle()
    font_style.borders = borders

    style2 = xlwt.easyxf('font: bold off, color black;\
                             align: horiz right')
    # cursor = connection.cursor()
    # cursor.execute('SELECT "REFERENSI"."REF_SKPD"."SKPD_KODE" skpd_kode,"REFERENSI"."REF_SKPD"."SKPD_NAMA" skpd_nama,program,kegiatan,sub_kegiatan,anggaran,apbd,dbhct,dak,tp,lainya FROM "MUSRENBANG".rekap_program_kegiatan RIGHT JOIN "REFERENSI"."REF_SKPD" ON "MUSRENBANG".rekap_program_kegiatan."SKPD_ID" = "REFERENSI"."REF_SKPD"."SKPD_ID" ORDER BY  skpd_kode asc')
    # # cursor.execute('select * from "REFERENSI"."REF_SKPD"')
    # Data = cursor.fetchall()
    print(Data)
    # for row in Data:
    for name, num in enumerate(Data):
        row_num += 1
        ws.write(row_num, 0, row_num, font_style)
        ws.write(row_num, 1, "{1}".format(name, num[1]) , font_style)
        ws.write(row_num, 2, "{1}".format(name, num[2]) , font_style)
        ws.write(row_num, 3, "{1}".format(name, num[3]) , font_style)
        ws.write(row_num, 4, "{1}".format(name, num[4]) , style2)
        ws.write(row_num, 5, "{1}".format(name, num[5]) , style2)
        ws.write(row_num, 6, "{1}".format(name, num[6]) , style2)
        ws.write(row_num, 7, "{1}".format(name, num[7]) , style2)

    wb.save(response)
    return response
def rekapAjuanKegiatanopd(request,opd_id=None):
    if opd_id is None:
        a='0'
        wh="where skpd_id="+a
        sql='select * from "MUSRENBANG".new_ajuan_kegiatan_opd '+wh+' order by  skpd_kode asc,program_kode asc, kegiatan_kode asc'
    else:
        wh="where skpd_id="+opd_id
        sql='select * from "MUSRENBANG".new_ajuan_kegiatan_opd '+wh+' order by  skpd_kode asc,program_kode asc, kegiatan_kode asc'

    cursor = connection.cursor()
    cursor.execute(sql)
    Data = cursor.fetchall()
    cursor = connection.cursor()
    cursor.execute('select "SKPD_ID","SKPD_NAMA" from "REFERENSI"."REF_SKPD"')
    Opd = cursor.fetchall()
    context = {
        'title'          : 'Ajuan Kegiatan OPD',
        'active_rekapAjuanKegiatanopd'    : 'active',
        'Data'           : Data,
        'Opd'           : Opd,
        'Opd_id'           : opd_id,
    }
    return render(request,'monitoring/rekapAjuanKegiatanopd.html',context)
def excel_view_rekapAjuanKegiatanopd(request,opd_id=None):
    if opd_id is '0':
        wh=''
        a='select * from "MUSRENBANG".new_laporan_ajuan_program_kegiatan_opd '+ wh
    else:
        wh="where skpd_id="+opd_id
        a='select * from "MUSRENBANG".new_ajuan_kegiatan_opd '+wh+' order by  skpd_kode asc,program_kode asc, kegiatan_kode asc'
    # return HttpResponse(a)
    cursor = connection.cursor()
    cursor.execute(a)
    Data = cursor.fetchall()
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename="Ajuan Kegiatan OPD.xls"'

    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('Ajuan Kegiatan OPD', cell_overwrite_ok=True)
    # Sheet header, first row
    row_num = 0
    # borders
    borders = xlwt.Borders()
    borders.left = 1
    borders.right = 1
    borders.top = 1
    borders.bottom = 1

    font_style = xlwt.XFStyle()
    font_style.font.bold = True
    font_style.borders = borders

    columns = ['No', 'Kode OPD', 'OPD', 'Kode Porgram','Program','Kode Kegiatan', 'Kegiatan','Sub Kegiatan','APBD', 'DBHCHT', 'DAK', 'TP', 'LAINNYA' ]
    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)

    #Format Currency
    style2 = xlwt.XFStyle()
    style2.num_format_str = '$#,##0.00'
    style2.borders = borders
    # Sheet body, remaining rows
    font_style = xlwt.XFStyle()
    font_style.borders = borders

    style2 = xlwt.easyxf('font: bold off, color black;\
                             align: horiz right')
    # cursor = connection.cursor()
    # cursor.execute('SELECT "REFERENSI"."REF_SKPD"."SKPD_KODE" skpd_kode,"REFERENSI"."REF_SKPD"."SKPD_NAMA" skpd_nama,program,kegiatan,sub_kegiatan,anggaran,apbd,dbhct,dak,tp,lainya FROM "MUSRENBANG".rekap_program_kegiatan RIGHT JOIN "REFERENSI"."REF_SKPD" ON "MUSRENBANG".rekap_program_kegiatan."SKPD_ID" = "REFERENSI"."REF_SKPD"."SKPD_ID" ORDER BY  skpd_kode asc')
    # # cursor.execute('select * from "REFERENSI"."REF_SKPD"')
    # Data = cursor.fetchall()
    print(Data)
    # for row in Data:
    for name, num in enumerate(Data):
        row_num += 1
        ws.write(row_num, 0, row_num, font_style)
        ws.write(row_num, 1, "{1}".format(name, num[2]) , font_style)
        ws.write(row_num, 2, "{1}".format(name, num[3]) , font_style)
        ws.write(row_num, 3, "{1}".format(name, num[6]) , font_style)
        ws.write(row_num, 4, "{1}".format(name, num[7]) , font_style)
        ws.write(row_num, 5, "{1}".format(name, num[8]) , font_style)
        ws.write(row_num, 6, "{1}".format(name, num[9]) , font_style)
        ws.write(row_num, 7, "{1}".format(name, num[10]) , font_style)
        ws.write(row_num, 8, "{1}".format(name, num[12]) , style2)
        ws.write(row_num, 9, "{1}".format(name, num[13]) , style2)
        ws.write(row_num, 10, "{1}".format(name, num[14]) , style2)
        ws.write(row_num, 11, "{1}".format(name, num[15]) , style2)
        ws.write(row_num, 12, "{1}".format(name, num[16]) , style2)

    wb.save(response)
    return response
def rekapAjuan(request):
    cursor = connection.cursor()
    cursor.execute('SELECT "REFERENSI"."REF_SKPD"."SKPD_KODE" skpd_kode,"REFERENSI"."REF_SKPD"."SKPD_NAMA" skpd_nama,program,kegiatan,sub_kegiatan,anggaran,apbd,dbhct,dak,tp,lainya FROM "MUSRENBANG".rekap_program_kegiatan RIGHT JOIN "REFERENSI"."REF_SKPD" ON "MUSRENBANG".rekap_program_kegiatan."SKPD_ID" = "REFERENSI"."REF_SKPD"."SKPD_ID" ORDER BY  skpd_kode asc')
    # cursor.execute('select * from "REFERENSI"."REF_SKPD"')
    Data = cursor.fetchall()
    # print(posts)
    context = {
        'title'          : 'Rekapitulasi Ajuan',
        'active_rekapAjuan'    : 'active',
        'Data'           : Data,
    }
    # print(Data)
    return render(request,'monitoring/rekapAjuan.html',context)
def excel_view(request):

    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename="Rekapitulasi Ajuan.xls"'

    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('Rekapitulasi Ajuan', cell_overwrite_ok=True)
    # Sheet header, first row
    row_num = 0
    # borders
    borders = xlwt.Borders()
    borders.left = 1
    borders.right = 1
    borders.top = 1
    borders.bottom = 1

    font_style = xlwt.XFStyle()
    font_style.font.bold = True
    font_style.borders = borders

    columns = ['No', 'Kode OPD', 'OPD', 'Porgram', 'Kegiatan','Sub Kegiatan','APBD','DBHCHT','DAK','TP','LAINYA','Total Anggaran' ]
    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)

    #Format Currency
    style2 = xlwt.XFStyle()
    style2.num_format_str = '$#,##0.00'
    style2.borders = borders
    # Sheet body, remaining rows
    font_style = xlwt.XFStyle()
    font_style.borders = borders

    style2 = xlwt.easyxf('font: bold off, color black;\
                             align: horiz right')
    cursor = connection.cursor()
    cursor.execute('SELECT "REFERENSI"."REF_SKPD"."SKPD_KODE" skpd_kode,"REFERENSI"."REF_SKPD"."SKPD_NAMA" skpd_nama,program,kegiatan,sub_kegiatan,anggaran,apbd,dbhct,dak,tp,lainya FROM "MUSRENBANG".rekap_program_kegiatan RIGHT JOIN "REFERENSI"."REF_SKPD" ON "MUSRENBANG".rekap_program_kegiatan."SKPD_ID" = "REFERENSI"."REF_SKPD"."SKPD_ID" ORDER BY  skpd_kode asc')
    # cursor.execute('select * from "REFERENSI"."REF_SKPD"')
    Data = cursor.fetchall()
    print(Data)
    # for row in Data:

monitoring/templates/monitoring/kegiatanEntry.html
{% extends 'base2.html' %}

{% block contents %}
{% load humanize %}
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
      <div class="card mb-3">
          <div class="card-header card-header-divider">{{title}}
            <div class="tools float-right">
              <div class="btn-group">
                <a href="#" class="btn btn-success btn-sm" id="print"><i class="mdi mdi-print" ></i> Cetak</a>
              </div>
            </div>
          </div>
          <div class="card-body">

            <div class="row">
                <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-xl-6">
                    <div class="form-group row pt-1">
                        <label class="col-3 col-sm-3 col-form-label text-sm-right">OPD</label>
                        <div class="col-12 col-sm-8 col-lg-6">
                            <select class="form-control form-control-xs" name="opd" id="opd" placeholder="OPD">

                                <option value="None" style="color:black">Pilih OPD</option>
                                {% for rk in Opd %}
                                  <option
                                     value="{{rk.0}}"
                                     {% if rk.0 == Opd_id %}
                                     selected="selected"
                                     {% endif %}>{{rk.1}}</option>
                                {% endfor %}

                            </select>
                      </div>
                  </div>
            </div>
                <table class="table table-responsive-xl table-bordered">
                  <thead>
                    <tr>
                        <th>No</th>
                        <th>Kode OPD</th>
                        <th>OPD</th>
                        <th>Kode Program </th>
                        <th>Program </th>
                        <th>Kode Kegiatan</th>
                        <th>Kegiatan</th>
                        <th>Sub Kegiatan</th>
                        <th>Anggaran</th>
                    </tr>
                  </thead>
                  <tbody>
                    <!-- {{Data}} -->
                    {% for rk in Data %}
                      <tr>
                        <td align="center">{{forloop.counter}}</td>
                        <td>{{rk.16}}</td>
                        <td>{{rk.17}}</td>
                        <td class="text-left">{{rk.5}}</td>
                        <td class="text-left">{{rk.6}}</td>
                        <td class="text-left">{{rk.2}}</td>
                        <td class="text-left">{{rk.3}}</td>
                        <td class="text-right">{{rk.9|intcomma }}</td>
                        <td class="text-right">{{rk.10|intcomma}}</td>
                      </tr>
                    {% endfor %}

                  </tbody>
                </table>
      </div><!-- end card-->
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
        $("#opd").val("{{Opd_id}}");
     $("#opd").on('change',function(e){
        opd = $('#opd').val();
        // alert(opd);
        var url_mask = '{% url "monitoring:kegiatanEntry" opd_id=1%}'.replace(/1/, opd.toString());
        window.location.href = url_mask;
      });
      $("#print").on('click',function(e){
        opd = $('#opd').val();
        // alert(opd);
        if (opd=='None') {
          opd=0
        }
        var url_mask = '{% url "monitoring:excel_view_kegiatanEntry" opd_id=1%}'.replace(/1/, opd.toString());
        window.location.href = url_mask;
      });
  });

</script>
{% endblock contents %}

monitoring/templates/monitoring/rekapAjuanKegiatanopd.html
{% extends 'base2.html' %}

{% block contents %}
{% load humanize %}
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
      <div class="card mb-3">
          <div class="card-header card-header-divider">{{title}}
            <div class="tools float-right">
              <div class="btn-group">

                {% if Data|length > 0 %}

                <a href="{% url "monitoring:excel_view_rekapAjuanKegiatanopd" opd_id=Opd_id%}" class="btn btn-success btn-sm" id="print"><i class="mdi mdi-print" ></i> Cetak</a>
                {% endif %}

              </div>
            </div>
          </div>
          <div class="card-body">

            <div class="row">
                <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-xl-6">
                    <div class="form-group row pt-1">
                        <label class="col-3 col-sm-3 col-form-label text-sm-right">OPD</label>
                        <div class="col-12 col-sm-8 col-lg-6">
                            <select class="form-control form-control-xs" name="opd" id="opd" placeholder="OPD">

                                <option value="None" style="color:black">Pilih OPD</option>
                                {% for rk in Opd %}
                                  <option
                                     value="{{rk.0}}"
                                     {% if rk.0 == Opd_id %}
                                     selected="selected"
                                     {% endif %}>{{rk.1}}</option>
                                {% endfor %}

                            </select>
                      </div>
                  </div>
            </div>

            {% if Data|length > 0 %}
            <div class="table-responsive">
            <table class="table table-responsive-xl table-bordered">
                <thead>
                  <tr>
                      <th width="3%">No </th>
                      <th>Kode OPD</th>
                      <th>OPD</th>
                      <th>Kode Program</th>
                      <th>Program</th>
                      <th>kode Kegiatan</th>
                      <th>Kegiatan</th>
                      <th>Sub Kegiatan</th>
                      <th>APBD</th>
                      <th>DBHCT</th>
                      <th>DAK</th>
                      <th>TP</th>
                      <th>LAINYA</th>
                  </tr>
                </thead>
                <tbody>
                  <!-- {{Data}} -->
                  {% for rk in Data %}
                    <tr>
                      <td align="center">{{forloop.counter}}</td>
                      <td>{{rk.2}}</td>
                      <td>{{rk.3}}</td>
                      <td class="text-left">{{rk.6}}</td>
                      <td class="text-left">{{rk.7}}</td>
                      <td class="text-left">{{rk.8}}</td>
                      <td class="text-left">{{rk.9}}</td>
                      <td class="text-left">{{rk.10}}</td>
                      <td class="text-right">{{rk.12|intcomma }}</td>
                      <td class="text-right">{{rk.13|intcomma}}</td>
                      <td class="text-right">{{rk.14|intcomma }}</td>
                      <td class="text-right">{{rk.15|intcomma}}</td>
                      <td class="text-right">{{rk.16|intcomma }}</td>
                    </tr>
                  {% endfor %}

                </tbody>
              </table>
              </div>
            {% endif %}

      </div><!-- end card-->
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
        $("#opd").val("{{Opd_id}}");
     $("#opd").on('change',function(e){
        opd = $('#opd').val();
        // alert(opd);
        var url_mask = '{% url "monitoring:rekapAjuanKegiatanopd" opd_id=1%}'.replace(/1/, opd.toString());
        window.location.href = url_mask;
      });
      // $("#print").on('click',function(e){
      //   opd = $('#opd').val();
      //   // alert(opd);
      //   if (opd=='None') {
      //     opd=0
      //   }
      //   var url_mask = '{% url "monitoring:excel_view_rekapAjuanopd" opd_id=1%}'.replace(/1/, opd.toString());
      //   window.location.href = url_mask;
      // });
  });

</script>
{% endblock contents %}

monitoring/templates/monitoring/renja2.html
{% extends 'base2.html' %}

{% block contents %}
{% load humanize %}
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
      <div class="card mb-3">
          <div class="card-header card-header-divider">{{title}}
            <div class="tools float-right">
              <div class="btn-group">

                {% if Data|length > 0 %}

                <a href="{% url "monitoring:excel_view_rekapAjuanKegiatanopd" opd_id=Opd_id%}" class="btn btn-success btn-sm" id="print"><i class="mdi mdi-print" ></i> Cetak</a>
                {% endif %}

              </div>
            </div>
          </div>
          <div class="card-body">

            <div class="row">
                <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-xl-6">
                    <div class="form-group row pt-1">
                        <label class="col-3 col-sm-3 col-form-label text-sm-right">OPD</label>
                        <div class="col-12 col-sm-8 col-lg-6">
                            <select class="form-control form-control-xs" name="opd" id="opd" placeholder="OPD">

                                <option value="None" style="color:black">Pilih OPD</option>
                                {% for rk in Opd %}
                                  <option
                                     value="{{rk.0}}"
                                     {% if rk.0 == Opd_id %}
                                     selected="selected"
                                     {% endif %}>{{rk.1}}</option>
                                {% endfor %}

                            </select>
                      </div>
                  </div>
            </div>

            {% if Data|length > 0 %}
            <div class="table-responsive">
            <table class="table table-responsive-xl table-bordered">
                <thead>
                    <tr>
                        <th align="center" rowspan="2"> No</th>
                        <th align="center" colspan="2">Program/Kegiatan</th>
                        <th align="center" rowspan="2">lokasi</th>
                        <th align="center" rowspan="2">Sasaran</th>
                        <th align="center" rowspan="2">Indikator Hasil /Indikator Keluaran</th>
                        <th align="center" rowspan="2">Target</th>
                        <th align="center" colspan="5">Usulan Anggaran</th>
                        <th align="center" rowspan="2">Prakiraan Maju Tahun</th>
                      </tr>
                      <tr>
                        <th align="center">kode</th>
                        <th align="center">Nama</th>
                        <th align="center">APBD</th>
                        <th align="center"> DBHCHT</th>
                        <th align="center">DAK</th>
                        <th align="center">TP</th>
                        <th align="center">Lainya</th>

                      </tr>
                      <tr>
                        <th align="center">1</th>
                        <th align="center">2</th>
                        <th align="center">3</th>
                        <th align="center">4</th>
                        <th align="center">5</th>
                        <th align="center">6</th>
                        <th align="center">7</th>
                        <th align="center">8</th>
                        <th align="center">9</th>
                        <th align="center">10</th>
                        <th align="center">11</th>
                        <th align="center">12</th>
                        <th align="center">13</th>
                      </tr>
                </thead>
                <tbody>
                    {% with PROGRAM_KODE="" greeting="Hello" %}
                  <!-- {{Data}} -->
                  {%  for rk in Data %}
                    <tr>
                      <td align="center">{{forloop.counter}}</td>
                      <!-- program -->

                      {% ifnotequal  PROGRAM_KODE rk.2 %}

                      <td>{{rk.2}}</td>
                      <td>{{rk.3}}</td>
                      {% else %}

                      <td></td>
                      <td></td>
                      {% endifnotequal  %}

                      <!-- end program -->
                      <td class="text-left">{{rk.4|default_if_none:''}}</td>
                      <td class="text-left">{{rk.5|default_if_none:''}}</td>
                      <td class="text-left">{{rk.6|default_if_none:''}}</td>
                      <td class="text-left">{{rk.7|default_if_none:''}} {{rk.8|default_if_none:''}}</td>
                      <td class="text-right">{{rk.9 |default_if_none:''|intcomma}}</td>
                      <td class="text-right">{{rk.10 |default_if_none:''|intcomma}}</td>
                      <td class="text-right">{{rk.11 |default_if_none:''|intcomma}}</td>
                      <td class="text-right">{{rk.12 |default_if_none:''|intcomma}}</td>
                      <td class="text-right">{{rk.13|default_if_none:''|intcomma}}</td>
                      <td>0</td>
                    </tr>

                    {% with  PROGRAM_KODE=rk.2  %}

                    {% endwith %}

                  {% endfor %}
                  {% endwith %}
                </tbody>
              </table>
              </div>
            {% endif %}

      </div><!-- end card-->
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
        $("#opd").val("{{Opd_id}}");
     $("#opd").on('change',function(e){
        opd = $('#opd').val();
        // alert(opd);
        var url_mask = '{% url "monitoring:renja2" opd_id=1%}'.replace(/1/, opd.toString());
        window.location.href = url_mask;
      });
      // $("#print").on('click',function(e){
      //   opd = $('#opd').val();
      //   // alert(opd);
      //   if (opd=='None') {
      //     opd=0
      //   }
      //   var url_mask = '{% url "monitoring:excel_view_rekapAjuanopd" opd_id=1%}'.replace(/1/, opd.toString());
      //   window.location.href = url_mask;
      // });
  });

</script>
{% endblock contents %}